# config/__init__.py

from .settings import (
    SUPPORTED_AUDIO_FORMATS,
    DEFAULT_API_URL,
    DEFAULT_AUTHORIZATION,
    DEFAULT_LANGUAGE,
    DEFAULT_TTS_VOICE,
    DEFAULT_USE_VOICE,
    DEFAULT_OUTPUT_DIR,
    DEFAULT_HEADERS
)

__all__ = [
    'SUPPORTED_AUDIO_FORMATS',
    'DEFAULT_API_URL',
    'DEFAULT_AUTHORIZATION',
    'DEFAULT_LANGUAGE',
    'DEFAULT_TTS_VOICE',
    'DEFAULT_USE_VOICE',
    'DEFAULT_OUTPUT_DIR',
    'DEFAULT_HEADERS'
]
